steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'function1'
    args:
      - functions
      - deploy
      - extractDailyData
      - --source=.
      - --entry-point=ExtractFunction
      - --trigger-http
      - --runtime=java11
  - name: 'function2'
      args:
        - functions
        - deploy
        - extractAnnouncements
        - --source=.
        - --entry-point=ExtractAnnouncementsFunction
        - --trigger-http
        - --runtime=java11