steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/data-extractor-image", "--build-arg=JAR_FILE=target/DataExtractor-1.0.0.jar", "."]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dataextractorservice'
      - '--image'
      - 'gcr.io/$PROJECT_ID/data-extractor-image'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images: ["gcr.io/$PROJECT_ID/data-extractor-image"]