steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - extractDailyData
      - --source=.
      - --entry-point=ExtractFunction
      - --trigger-http
      - --runtime=java11